version: "3.9"

services:
  jenkins:
    build:
      context: ./
      args:
        HOST_JENKINS_UID: ${HOST_JENKINS_UID}
        HOST_DOCKER_GID: ${HOST_DOCKER_GID}
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    restart: unless-stopped
    user: root
    privileged: true
    volumes:
      - $PWD/jenkins-data/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
